import os

X_RAPIDAPI_KEY = os.environ.get('X_RAPIDAPI_KEY')
GOOGLE_GEMINI_API_KEY = os.environ.get('GOOGLE_GEMINI_API_KEY')
GEMINI_MODEL = os.environ.get('GEMINI_MODEL')
TIKTOK_RAPID_API = os.environ.get('TIKTOK_RAPID_API')
TIKTOK_RAPID_HOST = os.environ.get('TIKTOK_RAPID_HOST')
YOUTUBE_RAPID_API = os.environ.get('YOUTUBE_RAPID_API')
YOUTUBE_RAPID_HOST = os.environ.get('YOUTUBE_RAPID_HOST')
FACEBOOK_RAPID_API = os.environ.get('FACEBOOK_RAPID_API')
FACEBOOK_RAPID_HOST = os.environ.get('FACEBOOK_RAPID_HOST')
DB_HOST = os.environ.get('DB_HOST')
DB_USER = os.environ.get('DB_USER')
DB_PASSWORD = os.environ.get('DB_PASSWORD')
DB_NAME = os.environ.get('DB_NAME')